version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'yyblog'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin@123'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - "3306:3306"
    volumes:
      - mysql-db-data:/var/lib/mysql
      - ./db_structure.sql:/docker-entrypoint-initdb.d/db_structure.sql
    command: --default-authentication-plugin=mysql_native_password

  yyblog:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql-db
    environment:
      DB_HOST: mysql-db
      DB_PORT: 3306
      DB_NAME: yyblog
      DB_USER: root
      DB_PASSWORD: root
      APP_DOMAIN: 127.0.0.1
    restart: always

volumes:
  mysql-db-data: